using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class Incremental_item : MonoBehaviour {

	//================================================================
	// NUMERICAL VALUES
	//================================================================
	public Economy_manager economyManager; //To subtract the total money to buy an object

	public double base_cost       = 1.0;    
	public double actual_cost     = 1.0;    
	public double augment_ratio   = 0.15;  //Increasing ratio of the cost value
	public double wps_per_unit    = 1;     //Waves per second
	public double wps_total       = 0;
	public int number_of_elements = 0;
	public int elements_till_next_item = 100; 	//Items needed to buy the next item on the list

	//================================================================
	// UI VALUES
	//================================================================
	public Button clicking_button; 	//Button to listen to when clicked
	public List<Text> inner_text; 	//Name of the object - current number of objects - value
	public string object_name; 		//Name of the object itself

	public Color32 base_txt_color;  //Color of the text at any given time
	public Color32 price_txt_color; //Color of the text at any given time

	// Use this for initialization
	void Start () {

	}

	// Update is called once per frame
	void Update () {

		//Update if the button can be clicked or what
		updateClickability();
	}

	void purchase()
	{
		//If it is clickable, then you can buy it
		if(!clicking_button.interactable)
			return;

		//Subtract value from global economy
		if(!economyManager.buy(actual_cost))
			return;

		//Add number of elements
		number_of_elements++;

		//Update total value generated by the objects
		wps_total = wps_per_unit * number_of_elements;

		//Augment the price
		actual_cost *= (1 + augment_ratio);

		//Update the text
		inner_text[0].text = object_name;
		inner_text[1].text = "" + actual_cost.ToString("F1");
		inner_text[2].text = "" + number_of_elements;

	}

	public void activate()
	{
		//================================================================
		// GET VARIABLES
		//================================================================
		//Button
		clicking_button = transform.GetComponent<Button>();

		//Inner text of the button
		inner_text = new List<Text>();
		Text[] t = transform.GetComponentsInChildren<Text>();
		foreach(Text t_aux in t)
		{
			inner_text.Add(t_aux);
		}

		//Find economy Manager
		economyManager = GameObject.FindWithTag("EconomyManager").GetComponent<Economy_manager>();

		//================================================================

		//Function to activate when pressed
		clicking_button.onClick.AddListener(purchase);

		//Set personal tag
		gameObject.tag = "IncrementalItem";

		//Enable button
		clicking_button.interactable = true;

		//Update the text for the first time
		inner_text[0].text = object_name;
		inner_text[1].text = "" + actual_cost.ToString("F1");
		inner_text[2].text = "" + number_of_elements;
	}

	void updateClickability()
	{
		//Verify if economy manager exists
		if(!economyManager)
			return;

		//First buy the object (if false you can't buy it, so animate a change in the text to red)
		if (!economyManager.can_buy (actual_cost))
		{
			clicking_button.interactable = false;
			return;
		}

		clicking_button.interactable = true;
	}


}
